version: '3.8'

services:
  retell-bridge:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - RETELL_API_KEY=key_1a1a1708db5526852b627eada45d
      - N8N_WEBHOOK_URL=https://n8n-n8n.nhuls8.easypanel.host/webhook/clinica-dental
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s