version: '3.8'

services:
  retell-dental-llm:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - RETELL_API_KEY=${RETELL_API_KEY}
      - OPENAI_APIKEY=${OPENAI_APIKEY}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.retell-dental.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.retell-dental.tls=true"
      - "traefik.http.routers.retell-dental.tls.certresolver=letsencrypt"